name: 1.58bit-flux
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - cudatoolkit=11.8
  - pip>=23.0
  - pip:
      # PyTorch 관련 패키지: index-url 명시
      - torch --index-url https://download.pytorch.org/whl/cu128
      - torchvision --index-url https://download.pytorch.org/whl/cu128
      - torchaudio --index-url https://download.pytorch.org/whl/cu128
      
      # 나머지는 기본 PyPI에서 설치
      - diffusers==0.34.0
      - transformers==4.41.0
      - accelerate==0.29.3
      - safetensors==0.4.4
      - pillow>=10.0
      - tqdm>=4.66
      - huggingface_hub>=0.23
      - sentencepiece
      - protobuf
