from typing import List

###############################################################################
# Default prompt set (100 diverse scenarios)
###############################################################################

_PROMPTS: List[str] = [
    "Cyberpunk samurai on a neon-lit rooftop at dusk, dramatic rim lighting, 32-bit render",
    "Golden retriever wearing vintage aviator goggles, photoreal, shallow depth of field",
    "Victorian library floating in space, warm candlelight, ultra-detailed, 8 k",
    "Surreal desert with giant hourglasses, pastel tones, Salvador Dali style",
    "Futuristic Tokyo street market in heavy rain, cinematic, wide-angle lens",
    "Medieval knight made of living vines and flowers, high fantasy illustration",
    "Steampunk submarine cockpit, brass and glass textures, volumetric lighting",
    "Ancient Greek temple carved into an iceberg, twilight, matte-painting quality",
    "Miniature city inside a glass terrarium, tilt-shift, hyper-real",
    "Retro sci-fi magazine cover of a rocket launch, 1950s color palette",
    "Concert pianist playing on a floating stage above the clouds, ethereal atmosphere",
    "Close-up portrait of an android with porcelain skin cracking, ultra realism",
    "Microscopic view of coral reef ecosystems, bright fluorescence, macro lens",
    "Abandoned amusement park overtaken by giant mushrooms, gloomy mood",
    "Astral dragon circling a black hole, cosmic dust, high contrast",
    "Art-deco metropolis at sunrise, golden hues, isometric perspective",
    "60s spy car chase through narrow European streets, motion blur, film grain",
    "Snow-covered cyber-monastery perched on a cliff, moody skylight",
    "Portrait of a pirate queen with bioluminescent tattoos, dark fantasy",
    "Glass chessboard with pieces made of water splashes, studio lighting",
    "Retro computer lab filled with CRT monitors, neon reflections, synthwave vibe",
    "Giant koi fish swimming through skyscrapers, dreamlike, double exposure",
    "Futuristic firefighter mech battling a skyscraper blaze, dynamic angle",
    "Ancient forest spirit emerging from mist, painterly, soft brush strokes",
    "Pixel-art cityscape at night, 16-bit palette, rain animation feel",
    "Time-lapse streaks of stars over an alien desert, long exposure photograph",
    "High-fashion runway on Mars, red dust swirling, Vogue editorial style",
    "Cutaway diagram of a colossal tree-city, educational illustration",
    "Robot barista serving latte art in a noir café, chiaroscuro lighting",
    "Gigantic origami crane unfolding over a river valley, sunrise glow",
    "Underground crystal cavern with bioluminescent waterfalls, 4 k realism",
    "Renaissance oil painting of astronauts eating grapes, anachronistic",
    "Neon graffiti alleyway populated by holographic cats, reflective puddles",
    "Stormy sea made of liquid mercury, monochrome, dramatic contrast",
    "Close-up of frost patterns forming fractals on glass, macro photography",
    "Medieval marketplace celebration at dusk, warm lantern light, crowd scene",
    "Futuristic samurai duel on a holographic bridge, particle effects",
    "Post-apocalyptic sunflower field with ruined wind turbines, hopeful tone",
    "Bioluminescent jellyfish sky lanterns drifting over a seaside town, whimsical",
    "Ancient astronaut hieroglyphs glowing inside a pyramid, mystic aura",
    "Cel-shaded mech riding a skateboard through a mall, comic-book panel",
    "Gothic cathedral interior built entirely of bones, eerie candlelight",
    "VR gamer wearing transparent HUD visor, cyan magenta lighting",
    "Epic mountain pass carved by giant dragons, panoramic matte painting",
    "Holographic koi pond in a zen office lobby, architectural visualization",
    "Underwater cyber-city with glass tunnels, ray-traced caustics",
    "Tiny astronaut exploring a mossy bonsai forest, whimsical macro",
    "Abstract splash of paint morphing into a dancer, motion capture style",
    "Vintage postcard of Jupiter’s Great Red Spot cruise, retro colors",
    "Steam locomotive racing across ice plains, dynamic perspective, 70 mm film look",
    "Neon-lit ramen stall run by robots, rainy night, cinematic bokeh",
    "Transparent mechanical pocket watch exploding into slow motion, high detail",
    "Fairy queen riding a hummingbird through lavender fields, pastel fantasy",
    "Cybernetic wolf with hologram fur, dark tech aesthetic",
    "Monochrome ink wash of samurai under falling cherry blossoms",
    "Isometric cutaway of an orbital space station farm, infographic style",
    "Art-nouveau poster of an electric violin concert, ornate typography",
    "Gigantic waffle city with syrup rivers, playful surrealism",
    "Wild west standoff on Mars, dusty red landscape, dramatic shadows",
    "Ancient rune-covered golem awakening in a storm, epic atmosphere",
    "Hyper-real chocolate lava cake exploding in zero gravity, food porn",
    "Futuristic medical lab with translucent hologram organs, clinical lighting",
    "Portrait of a cyber-witch casting digital runes, neon aura",
    "Snowy owl with galaxies in its eyes, mystical vibe",
    "Katana forged from pure lightning, comic splash art",
    "Retro arcade buzzing with pixel ghosts, vaporwave neon",
    "Floating iceberg hotel lobby, art-deco interior, sunrise reflections",
    "Moss-covered abandoned mech in the rainforest, melancholic mood",
    "Glitch art cityscape dissolving into code, RGB split",
    "Nordic longship sailing across clouds, fantasy realism",
    "Portrait of a noble lion wearing a crystal crown, regal lighting",
    "Underwater tea ceremony with mermaids, watercolor illustration",
    "1960s sci-fi family picnic on the moon, optimistic golden age style",
    "Cyberpunk herbalist mixing glowing potions, cluttered neon workshop",
    "Epic space battle seen through a cockpit HUD, high tension",
    "Kaleidoscopic fractal garden, vivid colors, symmetrical composition",
    "Haunted Victorian mirror reflecting a futuristic city, time paradox",
    "Close-up of mechanical butterfly wings opening, stainless steel texture",
    "Steampunk airship port at twilight, bustling crowd, warm glow",
    "Marble statue coming to life amid blooming roses, classical fantasy",
    "Astral projection of a meditating monk, cosmic lattice background",
    "Cyber-noir detective office bathed in teal and orange, cigarette smoke",
    "Rain-soaked neon jungle with electric vines, biopunk vibe",
    "Vintage diving suit exploring glowing deep-sea ruins, cinematic blue tones",
    "Desert nomad caravan of robotic camels, golden hour",
    "Gigantic library carved inside a whale skeleton, dark academia",
    "Retro holographic VHS cover of a mecha anime, grainy texture",
    "Candy-floss clouds floating over a mirror lake, dreamy pastel",
    "Photon dragon sculpted from pure light, celestial battlefield",
    "Galactic railgun firing across a purple nebula, vibrant sci-fi",
    "Miniature zen garden on a spaceship control panel, mixed scale",
    "Steampunk orchestra performing under a glass dome, intricate machinery",
    "Ice dragon breathing crystalline shards, high detail, back-lighting",
    "Photoreal splash of milk morphing into a crown, high-speed capture",
    "Samurai chef slicing sushi at lightning speed, humorous anime style",
    "Ancient stone archway opening to a cyber realm, contrast of eras",
    "Post-human city built on giant lotus flowers, golden sunset",
    "Futuristic Olympian racing on anti-gravity track, motion lines",
    "Crystal phoenix reborn from rainbow flames, fantasy illustration",
    "Neo-Tokyo skyline reflected in chrome koi scales, glossy finish",
]


def get_default_prompts() -> List[str]:
    return _PROMPTS