from typing import List

###############################################################################
# Default prompt set (100 diverse scenarios)
###############################################################################

_PROMPTS: List[str] = [
    "Cyberpunk samurai on a neon-lit rooftop at dusk, dramatic rim lighting, 32-bit render",
    "Golden retriever wearing vintage aviator goggles, photoreal, shallow depth of field",
    "Victorian library floating in space, warm candlelight, ultra-detailed, 8 k",
    "Surreal desert with giant hourglasses, pastel tones, Salvador Dali style",
    "Futuristic Tokyo street market in heavy rain, cinematic, wide-angle lens",
    "Medieval knight made of living vines and flowers, high fantasy illustration",
    "Steampunk submarine cockpit, brass and glass textures, volumetric lighting",
    "Ancient Greek temple carved into an iceberg, twilight, matte-painting quality",
    "Miniature city inside a glass terrarium, tilt-shift, hyper-real",
    "Retro sci-fi magazine cover of a rocket launch, 1950s color palette",
    "Concert pianist playing on a floating stage above the clouds, ethereal atmosphere",
    "Close-up portrait of an android with porcelain skin cracking, ultra realism",
    "Microscopic view of coral reef ecosystems, bright fluorescence, macro lens",
    "Abandoned amusement park overtaken by giant mushrooms, gloomy mood",
    "Astral dragon circling a black hole, cosmic dust, high contrast",
    "Art-deco metropolis at sunrise, golden hues, isometric perspective",
    "60s spy car chase through narrow European streets, motion blur, film grain",
    "Snow-covered cyber-monastery perched on a cliff, moody skylight",
    "Portrait of a pirate queen with bioluminescent tattoos, dark fantasy",
    "Glass chessboard with pieces made of water splashes, studio lighting",
    "Retro computer lab filled with CRT monitors, neon reflections, synthwave vibe",
    "Giant koi fish swimming through skyscrapers, dreamlike, double exposure",
    "Futuristic firefighter mech battling a skyscraper blaze, dynamic angle",
    "Ancient forest spirit emerging from mist, painterly, soft brush strokes",
    "Pixel-art cityscape at night, 16-bit palette, rain animation feel",
    "Time-lapse streaks of stars over an alien desert, long exposure photograph",
    "High-fashion runway on Mars, red dust swirling, Vogue editorial style",
    "Cutaway diagram of a colossal tree-city, educational illustration",
    "Robot barista serving latte art in a noir café, chiaroscuro lighting",
    "Gigantic origami crane unfolding over a river valley, sunrise glow",
    "Underground crystal cavern with bioluminescent waterfalls, 4 k realism",
    "Renaissance oil painting of astronauts eating grapes, anachronistic",
    "Neon graffiti alleyway populated by holographic cats, reflective puddles",
    "Stormy sea made of liquid mercury, monochrome, dramatic contrast",
    "Close-up of frost patterns forming fractals on glass, macro photography",
    "Medieval marketplace celebration at dusk, warm lantern light, crowd scene",
    "Futuristic samurai duel on a holographic bridge, particle effects",
    "Post-apocalyptic sunflower field with ruined wind turbines, hopeful tone",
    "Bioluminescent jellyfish sky lanterns drifting over a seaside town, whimsical",
    "Ancient astronaut hieroglyphs glowing inside a pyramid, mystic aura",
    "Cel-shaded mech riding a skateboard through a mall, comic-book panel",
    "Gothic cathedral interior built entirely of bones, eerie candlelight",
    "VR gamer wearing transparent HUD visor, cyan magenta lighting",
    "Epic mountain pass carved by giant dragons, panoramic matte painting",
    "Holographic koi pond in a zen office lobby, architectural visualization",
    "Underwater cyber-city with glass tunnels, ray-traced caustics",
    "Tiny astronaut exploring a mossy bonsai forest, whimsical macro",
    "Abstract splash of paint morphing into a dancer, motion capture style",
    "Vintage postcard of Jupiter’s Great Red Spot cruise, retro colors",
    "Steam locomotive racing across ice plains, dynamic perspective, 70 mm film look",
    "Neon-lit ramen stall run by robots, rainy night, cinematic bokeh",
    "Transparent mechanical pocket watch exploding into slow motion, high detail",
    "Fairy queen riding a hummingbird through lavender fields, pastel fantasy",
    "Cybernetic wolf with hologram fur, dark tech aesthetic",
    "Monochrome ink wash of samurai under falling cherry blossoms",
    "Isometric cutaway of an orbital space station farm, infographic style",
    "Art-nouveau poster of an electric violin concert, ornate typography",
    "Gigantic waffle city with syrup rivers, playful surrealism",
    "Wild west standoff on Mars, dusty red landscape, dramatic shadows",
    "Ancient rune-covered golem awakening in a storm, epic atmosphere",
    "Hyper-real chocolate lava cake exploding in zero gravity, food porn",
    "Futuristic medical lab with translucent hologram organs, clinical lighting",
    "Portrait of a cyber-witch casting digital runes, neon aura",
    "Snowy owl with galaxies in its eyes, mystical vibe",
    "Katana forged from pure lightning, comic splash art",
    "Retro arcade buzzing with pixel ghosts, vaporwave neon",
    "Floating iceberg hotel lobby, art-deco interior, sunrise reflections",
    "Moss-covered abandoned mech in the rainforest, melancholic mood",
    "Glitch art cityscape dissolving into code, RGB split",
    "Nordic longship sailing across clouds, fantasy realism",
    "Portrait of a noble lion wearing a crystal crown, regal lighting",
    "Underwater tea ceremony with mermaids, watercolor illustration",
    "1960s sci-fi family picnic on the moon, optimistic golden age style",
    "Cyberpunk herbalist mixing glowing potions, cluttered neon workshop",
    "Epic space battle seen through a cockpit HUD, high tension",
    "Kaleidoscopic fractal garden, vivid colors, symmetrical composition",
    "Haunted Victorian mirror reflecting a futuristic city, time paradox",
    "Close-up of mechanical butterfly wings opening, stainless steel texture",
    "Steampunk airship port at twilight, bustling crowd, warm glow",
    "Marble statue coming to life amid blooming roses, classical fantasy",
    "Astral projection of a meditating monk, cosmic lattice background",
    "Cyber-noir detective office bathed in teal and orange, cigarette smoke",
    "Rain-soaked neon jungle with electric vines, biopunk vibe",
    "Vintage diving suit exploring glowing deep-sea ruins, cinematic blue tones",
    "Desert nomad caravan of robotic camels, golden hour",
    "Gigantic library carved inside a whale skeleton, dark academia",
    "Retro holographic VHS cover of a mecha anime, grainy texture",
    "Candy-floss clouds floating over a mirror lake, dreamy pastel",
    "Photon dragon sculpted from pure light, celestial battlefield",
    "Galactic railgun firing across a purple nebula, vibrant sci-fi",
    "Miniature zen garden on a spaceship control panel, mixed scale",
    "Steampunk orchestra performing under a glass dome, intricate machinery",
    "Ice dragon breathing crystalline shards, high detail, back-lighting",
    "Photoreal splash of milk morphing into a crown, high-speed capture",
    "Samurai chef slicing sushi at lightning speed, humorous anime style",
    "Ancient stone archway opening to a cyber realm, contrast of eras",
    "Post-human city built on giant lotus flowers, golden sunset",
    "Futuristic Olympian racing on anti-gravity track, motion lines",
    "Crystal phoenix reborn from rainbow flames, fantasy illustration",
    "Neo-Tokyo skyline reflected in chrome koi scales, glossy finish",
    "A cyberpunk girl with neon tattoos walking through rainy Tokyo at night",
    "A medieval knight with glowing blue eyes standing on a cliff at sunset",
    "A robot barista serving coffee in a futuristic café",
    "An elf archer in a moonlit forest",
    "A pirate queen holding a glowing map under stormy skies",
    "A painter with a flower crown, surrounded by floating brushes",
    "A shadowy assassin in a misty alley",
    "A time traveler with a glowing wristwatch in 1980s New York",
    "A boy riding a mechanical dragon over a desert",
    "A mysterious magician with a levitating orb in front of him",
    "A floating island with waterfalls falling into clouds",
    "A futuristic city inside a transparent dome",
    "A lost temple in the heart of the jungle, overgrown with moss",
    "A neon-lit alley with steam rising from manholes",
    "A serene lake under aurora lights",
    "A beach on another planet with purple sand and twin suns",
    "A city made entirely of glass under a crimson sky",
    "A valley with flying whales and upside-down mountains",
    "A frozen castle made of ice crystals glowing from within",
    "An abandoned amusement park overgrown with vines",
    "A phoenix rising from volcanic ash",
    "A baby dragon curled up on a pile of books",
    "A cybernetic lion roaring in the digital jungle",
    "A deer with galaxies swirling in its antlers",
    "A jellyfish-shaped airship floating above a futuristic ocean",
    "A mechanical bird mid-flight with sparks coming off its wings",
    "A massive sea serpent swimming under icy waters",
    "A winged cat perched on a steampunk clock tower",
    "A glowing forest fox with nine tails",
    "A hybrid panda-unicorn floating on a cloud",
    "A dystopian city under military surveillance",
    "A moon base colony with astronauts farming mushrooms",
    "A spaceship graveyard orbiting Saturn",
    "A robot uprising in a ruined shopping mall",
    "A hacker operating under candlelight in a post-electric world",
    "A humanoid AI learning to paint",
    "A hovercar traffic jam in a vertical city",
    "A desert market run by alien merchants",
    "A VR arena battle between digital avatars",
    "A machine repairing itself in a rainstorm",
    "A spellcaster drawing runes in the air",
    "A floating castle connected by chains",
    "A witch flying over a glowing swamp",
    "A sword stuck in a tree instead of a stone",
    "A magical library with flying books and glowing floors",
    "A hidden portal inside a mirror in a forest",
    "A town built on the back of a giant turtle",
    "A dwarf blacksmith forging weapons in lava light",
    "A haunted mansion with eyes in the windows",
    "A rainbow bridge guarded by stone golems",
    "A dreamscape made of melting clocks and floating eyes",
    "A mind map as a glowing labyrinth",
    "A stairway leading into space",
    "Emotions visualized as colored smoke in a glass jar",
    "A person turning into butterflies",
    "A surreal cafe on top of a cloud",
    "An infinite hallway made of mirrors",
    "A glowing orb protected by shadowy hands",
    "A silhouette filled with a starfield",
    "A city that folds in on itself like origami",
    "A samurai standing in cherry blossoms during snowfall",
    "An Egyptian queen walking through a neon pyramid",
    "A Viking ship sailing through space",
    "A Renaissance painter surrounded by digital code",
    "A Roman gladiator inside a virtual arena",
    "A Korean palace merged with cyberpunk aesthetics",
    "A cowboy riding a hover horse in a desert",
    "A steampunk pharaoh ruling over mechanical slaves",
    "A French revolution scene in a futuristic Paris",
    "A Shakespearean actor performing on a hologram stage",
    "A cat wearing a space helmet floating in zero gravity",
    "A penguin detective with a magnifying glass",
    "A baby elephant painting with its trunk",
    "A group of frogs in a jazz band",
    "A corgi astronaut exploring a cookie planet",
    "A hamster sushi chef",
    "A chibi knight riding a snail",
    "A flock of birds wearing party hats",
    "A panda playing VR games",
    "A bunny magician pulling a carrot from a hat",
    "A low-poly mountain range at sunrise",
    "A pixel art version of a rainy city",
    "A watercolor landscape with cherry trees",
    "A manga-style girl flying in the sky",
    "A photorealistic steampunk motorcycle",
    "A claymation version of a robot dog",
    "A cubist interpretation of a city street",
    "A charcoal sketch of a burning forest",
    "A pastel world with floating pastries",
    "A 1980s anime-inspired space battle",
    "A health bar embedded into a knight’s armor",
    "A game loading screen in a fantasy dungeon",
    "An RPG-style menu over a real-world landscape",
    "A glowing cursor navigating an abandoned OS",
    "A split-screen co-op dungeon run",
    "A puzzle room with moving walls and riddles",
    "A pixelated enemy boss with 3 phases",
    "A turn-based battle HUD with alien creatures",
    "A character customization screen with sliders",
    "A retro arcade with neon screens and vaporwave soundtrack",
    "A librarian with floating books orbiting her head",
    "A detective in a noir city holding an umbrella under neon lights",
    "A shapeshifter mid-transformation in front of a mirror",
    "A rockstar with a flaming guitar on a floating stage",
    "A ballet dancer made of light particles",
    "A gardener planting stars in a moonlit garden",
    "A cowboy made of smoke",
    "A painter who uses sound instead of brushes",
    "A masked vigilante on a rainy rooftop",
    "A jazz saxophonist with glowing tattoos in a smoky lounge",
    "A canyon with glowing crystals embedded in the walls",
    "A desert with levitating pyramids",
    "A city built into the side of a giant cliff",
    "A jungle with bio-luminescent plants and fog",
    "An underwater marketplace lit by jellyfish lanterns",
    "A mountaintop observatory above the clouds",
    "A planet with floating lava rivers and icy skies",
    "A sky bridge connecting two skyscrapers in a future metropolis",
    "A forest made entirely of glass trees",
    "A train station in a parallel universe",
    "A human face made of flowers slowly blooming",
    "A clock tower melting into a field of wheat",
    "A staircase looping into itself like a Möbius strip",
    "A tear-shaped island floating in the void",
    "A candle with a galaxy flame",
    "A tree growing out of an open book",
    "A storm made of sheet music",
    "A human made entirely of butterflies",
    "A city reflected in someone’s eye",
    "A tornado frozen in time",
    "A cyborg with glass skin revealing circuits inside",
    "A data center cathedral with stained glass screens",
    "A soldier in exoskeleton armor scanning a ruined battlefield",
    "A hacker diving into a virtual city of code",
    "A vending machine that dispenses memories",
    "A robot gardener trimming binary-coded plants",
    "A drone swarm forming a whale in the sky",
    "A mechanical centaur on a racetrack",
    "A synthetic jungle built for AI wildlife",
    "A time dilation chamber collapsing into itself",
    "A crystal dragon sleeping inside a snow globe",
    "A witch baking potions in a candy forest",
    "A moon made of cheese guarded by mice",
    "A magical bakery with talking pastries",
    "A wizard fighting with musical notes",
    "A circus in the clouds with flying trapeze fairies",
    "A haunted toy shop where dolls whisper",
    "A village where everyone floats instead of walks",
    "A mirror maze that shows alternate lives",
    "A train that travels through dreams",
    "A samurai in ancient Rome",
    "A pharaoh using a hologram map",
    "A Korean hanbok-wearing android",
    "A traditional tea house on a space station",
    "A Native American warrior riding a robot horse",
    "A medieval banquet with floating digital menus",
    "A Renaissance monk discovering an iPad",
    "A Mayan temple reconstructed in glass",
    "A Mongolian yurt in the middle of a neon desert",
    "A 1930s jazz club on the moon",
    "A cat with butterfly wings lounging on a sunflower",
    "A llama covered in armor with LED eyes",
    "A parrot made entirely of crystals",
    "A chameleon blending into a pixel background",
    "A snail with a galaxy spiral shell",
    "A unicorn with circuitry instead of a horn",
    "A goldfish swimming through the air",
    "A peacock whose feathers display other worlds",
    "A spider weaving a web made of stars",
    "A firefly the size of a horse",
    "A chessboard where the pieces are alive and fighting",
    "A subway where the passengers are mythological creatures",
    "A rooftop garden in the clouds",
    "A carnival in zero gravity",
    "A rainy street where puddles show different dimensions",
    "A classroom run by sentient plants",
    "A dinner party with characters from fairy tales",
    "A marketplace where you can buy dreams",
    "A bus stop at the edge of the universe",
    "A waiting room for souls before reincarnation",
    "A street scene in the style of Van Gogh",
    "A robot in an ukiyo-e woodblock print",
    "A dancer illustrated in 1930s Disney style",
    "A cyberpunk skyline in pixel art",
    "A vaporwave forest trail",
    "A spaceship rendered in watercolor",
    "A graffiti wall depicting a fantasy battle",
    "A noir scene in charcoal sketch style",
    "A dream sequence in children's picture book aesthetic",
    "A villain lair designed like a Bauhaus painting",
    "A loading screen showing the creation of a new planet",
    "A main menu UI over a dungeon corridor",
    "An inventory screen inside a wizard’s bag",
    "A dating sim with alien characters",
    "A level-up animation for a time mage",
    "A health potion with personality",
    "A map that redraws itself as you walk",
    "A strategy game set in the subconscious",
    "A battle log written in ancient runes",
    "A player character choosing morality stats in front of a mirror",
]


def get_default_prompts() -> List[str]:
    return _PROMPTS